env:
  mode: "debug" # debug, release
  log_level: "debug" # 日志级别 debug, info, warn, error, fatal, panic, trace
server:
  port: 8080 # API服务端口

docker:
  image_name: "joedwards32/cs2" # 镜像名称
  tag: "latest" # 镜像标签
  volume_name: "cs2panel" # 卷名称
  prefix: "cs2panel" # 镜像前缀
  max_retries: 3 # 重连重试次数
  retry_delay: 1 # 重连重试间隔

util:
  log_dir: "./logs" # 日志路径
  log_filename: "app.log" # 日志文件名
  log_max_size: 10 # 日志文件大小，单位MB
  log_max_backups: 5 # 日志文件最大备份数
  log_max_age: 30 # 日志文件最大保存天数
  log_compress: true # 是否压缩日志文件

game:
  srcds_token: "0CB0CF618FD85A917FAC3F074244E801" # SRCDS_TOKEN
  rcon_password: "123456"
